language: go

go:
  - "1.6.x"  # ubuntu 16.04
  - "1.7.x"  # debian stable
  - "1.10.x" # ubuntu 18.04
  - "1.x"    # latest release

install:
  - go get golang.org/x/lint/golint

script:
  - go vet ./...
  - golint ./...
  - go test -v -cover ./...
